name: Next step for your template...
description: Setup Repository Details
labels: [setup-repository]

title: "Setup Repository"

body:
- type: input
  id: project_name
  attributes:
    label: Project Name
  validations:
    required: true
    
- type: input
  id: author_name
  attributes:
    label: Author
  validations:
    required: true

- type: input
  id: description
  attributes:
    label: Description
  validations:
    required: true

- type: dropdown
  id: open_source_license
  attributes:
    label: Choose your preferred license
    options:
      - MIT
      - BSD-3-Clause
      - No license file
  validations:
    required: true
    
- type: input
  id: s3_bucket
  attributes:
    label: S3 Bucket URI
    description: |
      You may not already have a bucket created, or not desire to use this, 
      if that is the case, just type in a placeholder so you can continue 
      setting up your project.
    placeholder: s3://yourbucketname/
  validations:
    required: true

- type: input
  id: aws_profile
  attributes:
    label: AWS Profile
    description: |
      You may not already have a bucket created, or not desire to use this, 
      if that is the case, just type in a placeholder so you can continue 
      setting up your project.
    placeholder: default
  validations:
    required: true
